package se.sics.ms.ui;

import se.sics.ms.configuration.MsConfig;
import se.sics.ms.types.IndexEntry;

import javax.swing.*;
import java.util.Date;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author jdowling
 */
public class AddIndexEntrySwingUi extends javax.swing.JDialog {

    private final UiComponent component;

    /**
     * Creates new form AddIndexEntrySwingUi
     */
    public AddIndexEntrySwingUi(java.awt.Frame parent, boolean modal,
            final UiComponent component) {
        super(parent, modal);
        initComponents();
        this.component = component;
    

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        root = new javax.swing.JPanel();
        fileNameField = new javax.swing.JTextField();
        fileSizeField = new javax.swing.JTextField();
        languageField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        categoryBox = new javax.swing.JComboBox();
        addIndexEntryButton = new javax.swing.JButton();
        urlField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        descriptionTextArea.setColumns(20);
        descriptionTextArea.setRows(5);
        jScrollPane1.setViewportView(descriptionTextArea);

        categoryBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "video", "music", "book" }));

        addIndexEntryButton.setText("Add Entry");
        addIndexEntryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addIndexEntryButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("url");

        jLabel2.setText("filename");

        jLabel3.setText("file size");

        jLabel4.setText("language");

        jLabel5.setText("category");

        jLabel6.setText("description");

        javax.swing.GroupLayout rootLayout = new javax.swing.GroupLayout(root);
        root.setLayout(rootLayout);
        rootLayout.setHorizontalGroup(
            rootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootLayout.createSequentialGroup()
                .addGroup(rootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rootLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(rootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(rootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(fileNameField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fileSizeField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(languageField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                            .addComponent(urlField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(categoryBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(rootLayout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(addIndexEntryButton)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        rootLayout.setVerticalGroup(
            rootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(rootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(urlField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileSizeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(12, 12, 12)
                .addGroup(rootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(languageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(12, 12, 12)
                .addGroup(rootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(addIndexEntryButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(root, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(root, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addIndexEntryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addIndexEntryButtonActionPerformed
                if(urlField.getText() == null) return;
                if(fileNameField.getText() == null) return;
                if(fileSizeField.getText() == null) return;
                if(languageField.getText() == null) return;
                if(descriptionTextArea.getText() == null) return;

                addIndexEntryButton.setEnabled(false);

                int selectedCategory = categoryBox.getSelectedIndex();

                IndexEntry entry = new IndexEntry(urlField.getText(), fileNameField.getText(), Long.parseLong(fileSizeField.getText()),
                        new Date(), languageField.getText(), MsConfig.Categories.values()[selectedCategory], descriptionTextArea.getText());

                component.addIndexEntry(entry);
                
    }//GEN-LAST:event_addIndexEntryButtonActionPerformed

    public void showAddResult(boolean isSuccessful) {
        String result;
        if (isSuccessful) {
            result = "Entry was successfully added";
        } else {
            result = "Failed to add an entry, try again";
        }

        Object[] options = {"OK"};
        JOptionPane.showOptionDialog(root,
                result, "Result on Add Index Entry",
                JOptionPane.PLAIN_MESSAGE,
                JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[0]);

        addIndexEntryButton.setEnabled(true);

    }

    public JPanel getRoot() {
        return root;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addIndexEntryButton;
    private javax.swing.JComboBox categoryBox;
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JTextField fileNameField;
    private javax.swing.JTextField fileSizeField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField languageField;
    private javax.swing.JPanel root;
    private javax.swing.JTextField urlField;
    // End of variables declaration//GEN-END:variables
}
