

package se.sics.ms.events.paginateAware;

import se.sics.kompics.KompicsEvent;
import se.sics.ms.types.SearchPattern;
import se.sics.ms.util.PaginateInfo;

/**
 * Search request generated by the client to the
 * application.
 *
 * Created by babbar on 2015-07-23.
 */
public class UiSearchRequest implements KompicsEvent{

    private SearchPattern pattern;
    private PaginateInfo paginateInfo;

    public UiSearchRequest(SearchPattern pattern, PaginateInfo paginateInfo) {
        this.pattern = pattern;
        this.paginateInfo = paginateInfo;
    }

    public SearchPattern getPattern(){
        return this.pattern;
    }

    public PaginateInfo getPaginateInfo(){
        return this.paginateInfo;
    }
}
