

package se.sics.ms.events.paginateAware;

import se.sics.kompics.KompicsEvent;
import se.sics.ms.types.ApplicationEntry;
import se.sics.ms.types.SearchPattern;
import se.sics.ms.util.PaginateInfo;

import java.util.Collection;

/**
 * Response for the search request generated by the application.
 *
 * Created by babbar on 2015-07-23.
 */
public class UiSearchResponse implements KompicsEvent{


    private SearchPattern searchPattern;
    private PaginateInfo paginateInfo;
    private int numHits;
    private Collection<ApplicationEntry> entries;

    public UiSearchResponse(SearchPattern searchPattern, PaginateInfo paginateInfo, int numHits, Collection<ApplicationEntry> entries) {

        this.searchPattern = searchPattern;
        this.paginateInfo = paginateInfo;
        this.numHits = numHits;
        this.entries = entries;
    }

    @Override
    public String toString() {
        return "UiSearchResponse{" +  "\n" +
                "searchPattern=" + searchPattern + "\n" +
                ", paginateInfo=" + paginateInfo +  "\n" +
                ", numHits=" + numHits + "\n" +
                ", entries=" + entries + "\n" +
                '}';
    }

    public SearchPattern getSearchPattern() {
        return searchPattern;
    }

    public PaginateInfo getPaginateInfo() {
        return paginateInfo;
    }

    public int getNumHits() {
        return numHits;
    }

    public Collection<ApplicationEntry> getEntries() {
        return entries;
    }
}
